NAME = push_swap
CC = cc
FLAGS = -Werror -Wextra -Wall

LIBFT_PATH = libs/libft
LIBFT = $(LIBFT_PATH)/libft.a

SRC = ./moves/push.c\
	./moves/push.c\
	./moves/r_reverse.c\
	./moves/r_reverse.c\
	./manager/control.c\
	./manager/is_sorted.c\
	./manager/parser.c\
	./manager/stack_manage.c\
	utils.c\
	